- name: Install and start httpd
  hosts: all
  become: yes

  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present
      notify: Install git if httpd is installed

    - name: Start httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: Install git if httpd is installed
      ansible.builtin.dnf:
        name: git
        state: present
